import Header from "../../components/Navigation"
import CallToAction from "../../components/CallToAction"
import Footer from "../../components/Footer"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"


export default function Home() {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main>
        <div className="py-32">
        <h2 className="text-3xl font-bold text-center mb-12 text-gray-900">Disclaimer</h2>
        <div className="flex justify-center text-center text-gray-700 mb-12 p-4">
            <div className="w-2/3 md:w-1/2">
              <div className="max-w-3xl mx-auto space-y-8 p-4 sm:p-6 bg-gray-100 rounded-sm">
                <div className="space-y-4 text-left">
                  <p className="text-sm text-gray-500 mb-6">Last updated: 1-3-'25</p>
                  <h3 className="text-xl font-semibold">Service Disclaimer</h3>
                  <p className="text-gray-600">Bitfeed is a platform that facilitates content management and AI integration. We are not responsible for:</p>
                  <ul className="list-disc pl-6 text-gray-600">
                    <li>Content generated by AI services</li>
                    <li>Third-party API costs or availability</li>
                    <li>User-created content and feeds</li>
                  </ul>
                  <h3 className="text-xl font-semibold">Usage</h3>
                  <p className="text-gray-600">Users are responsible for ensuring their use of Bitfeed complies with applicable laws and service provider terms.</p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <CallToAction />
      </main>
      <Footer />
    </div>
  )
}